all:
	pandoc -o README.rst README.md

# experimental autogenerated interface documentation
docopts := --include members.documented --markdown 3
autodoc:
	rm -r docs/build; mkdir docs/build
	cp docs/interface.md docs/build/interface.md
	inspect googleanalytics/auth/__init__.py $(docopts) >> docs/build/interface.md
	inspect googleanalytics/account.py $(docopts) >> docs/build/interface.md
	inspect googleanalytics/query.py $(docopts) >> docs/build/interface.md
	cp docs/build/interface.md docs/google-analytics.wiki/Interface.md
	cd docs/google-analytics.wiki && git add . --all && git commit \
		--message "Update autogenerated interface documentation."

test:
	python setup.py test

upload:
	python setup.py sdist upload
