all: wiki

# experimental autogenerated interface documentation
doc_fn := --include documented --markdown 5
doc_cls := --include members.documented --markdown 5
.PHONY: docs
docs:
	rm -r docs/build; mkdir docs/build
	cp docs/Interface.md docs/build/Interface.md
	inspect googleanalytics.auth $(doc_fn) >> docs/build/Interface.md
	#inspect googleanalytics.account $(doc_cls) >> docs/build/Interface.md
	inspect googleanalytics.query $(doc_cls) >> docs/build/Interface.md
	cp docs/build/Interface.md docs/google-analytics.wiki/Interface.md
	pandoc -o README.rst README.md

test:
	python setup.py test

wiki: docs
	cd docs/google-analytics.wiki && git add . --all && \
	git commit --message "Update autogenerated interface documentation." && \
	git push

package: docs
	python setup.py sdist upload
