all: wiki

# experimental autogenerated interface documentation
doc_fn := --include documented --markdown 5
doc_cls := --include members.documented --markdown 5
.PHONY: docs
docs:
	inspect googleanalytics.auth $(doc_fn) > docs/google-analytics.wiki/Python\ API\ Reference/auth.md
	inspect googleanalytics.account $(doc_cls) > docs/google-analytics.wiki/Python\ API\ Reference/Account.md
	inspect googleanalytics.query $(doc_cls) > docs/google-analytics.wiki/Python\ API\ Reference/Query.md
	pandoc -o README.rst README.md

test:
	python setup.py test

wiki: docs
	cd docs/google-analytics.wiki && git add . --all && \
	git commit --message "Update autogenerated interface documentation." && \
	git push

package: docs
	python setup.py sdist upload
